<!DOCTYPE html>
<html lang="en">
    <body>
        <section id="messages" >
            <?php foreach ($messageList as $msg) : ?>
                <div class="message" style="clear:both;">
                    <span class='msg-time'>
                        [<?php echo $this->escapeHtml($msg['time']); ?>]
                    </span>
                    <span class='msg-user'>
                        <?php echo $this->escapeHtml($msg['user']); ?>:
                    </span>
                    <span class='msg-data'>
                        <?php echo $this->escapeHtml($msg['data']); ?>
                    </span>
                </div>
            <?php endforeach; ?>
        </section>
    </body>
</html>