<?php
$title = 'Edit User Information';
$this->headTitle($title);
?>
<section class="edit">
    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <?php if ($this->error): ?>
    <p class="error">
        There were one or more issues with your submission.
        Please correct them as indicated below.
    </p>
    <?php endif; ?>
    
    <?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('users/user-manager', array(
        //'controller'=>'UserManager', 
        'action'=>'process')
    ));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd>
            <?php 
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?>
        </dd>
        <br />
        <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd>
            <?php 
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </dd>
        <br />
        <dd>
            <?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </dl>
    <?php echo $this->formElement($form->get('id')); ?>
    <?php echo $this->form()->closeTag(); ?>
</section>