<?php
$title = 'Register';
$this->headTitle($title);
?>
<section class="register">
    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issus with your submission. Please correct them as indicated below.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Register', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <dt>
            <?php echo $this->formLabel($form->get('name')); ?>
        </dt>
        <dd>
            <?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?>
        </dd>
        <br />
        <dt>
            <?php 
            echo $this->formLabel($form->get('email')); 
            ?>
        </dt>
        <dd><?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </dd>
        <br />
        <dt>
            <?php 
            echo $this->formLabel($form->get('password')); 
            ?>
        </dt>
        <dd>
            <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
        </dd>
        <br />
        <dt>
            <?php 
            echo $this->formLabel($form->get('confirm_password')); 
            ?>
        </dt>
        <dd>
            <?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?>
        </dd>
        <br />
        <dd>
            <?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </dl>
        <?php echo $this->form()->closeTag() ?>
</section>